### ISSUE TITLE
Add a tracker for first visits

### ISSUE THREAD

**Issue by viktor-yunenko** [rtcharity/eahub.org#1172]

**Comment by sebgrebe** [comment]
### Current state 
* We used to track whether someone is on their profile page by sending people after sign up to profile/first_visit. 
* The point of this was partly analytics, but also to prompt users to fill the profile with as  much info as possible. (This was a requst from @cafelow)  
This no longer w* orks, because we switched on email verification and users will first have to go to their inbox and click on a link there to go to their profile. This link is autogenerated and different from profile/first_visit  

### Desired state
* We can detect that someone is visiting their profile for the first time 
* When someone is visiting their profile for the first time, we nudge them to provide more info about themselves (can use the message box we were so far using for this)
* We can track in GA when someone is visiting their profile for their first time
and prompt them to

**Comment by sebgrebe** [comment]
@victor-yunenko maybe this could be a nice ```Good First Issue```?

**Comment by viktor-yunenko** [comment]
Not sure, there's ambiguity regarding the DB structure and the state management

**Comment by sebgrebe** [comment]
OK, let's try and define it together on Sunday

**Comment by viktor-yunenko** [comment]
@sebgrebe, in the meantime could you remind me the exact purpose of it?

For the data analysis - the first visit is the email confirmation timestamp. I'm not sure how this information helps in GA?

> When someone is visiting their profile for the first time, we nudge them to provide more info about themselves (can use the message box we were so far using for this)

Big social networks as eg linkedin or facebook would softly nudge when that information isn't filled, regardless of visit count.

**Comment by viktor-yunenko** [comment]
From UX point of view it sounds that if the user needs additional nudging, then the interface has an issue that I would rather address instead.

**Comment by viktor-yunenko** [comment]
For example I propose to redirect the user to `/profile/edit/` instead of `/profile/` after the email confirmation. The user needs to fill in that information, hence I don't want to ask them to do any manual clicks on "edit" buttons.

**Comment by sebgrebe** [comment]
closed, will be handled with #1185
