### ISSUE TITLE
Write more unit & end-to-end tests

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#165]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199658157929710/1199874506644562) by [Unito](https://www.unito.io/learn-more)

**Comment by sebgrebe** [comment]
@taymonbeal I'd be happy to get this started and write some very simple tests. Would use [puppeteer](https://github.com/GoogleChrome/puppeteer) for this. 
Is this OK with you?

**Comment by taymonbeal** [comment]
Puppeteer has a nice API, but I'm uneasy about using a framework that only works with Chrome. Selenium would allow the same tests to also run in Firefox (trivially) and Safari (with additional setup work), both of which we presumably want to support. (Also other browsers but we probably don't care about them.)

I think there's also an argument for writing the tests in Python rather than JavaScript, to reduce the amount of configuration involved and to make it easier to contribute (e.g., we can just point people to obeythetestinggoat.com for guidance). But less confident in this. I think it's more true if the amount of sophisticated JavaScript logic is expected to remain relatively small, e.g., we don't anticipate becoming a single-page app.

**Comment by sebgrebe** [comment]
Both fair points. I wonder though whether a good-enough solution is preferable to the ideal solution. I've already written a number of integration tests for the app with puppeteer and could relatively quickly build on this. I'd rather have some basic end-to-end tests that cover the basic functionalities than risk not having any because we worry about things like behaviour in different browsers. I just see the danger that writing those tests will always feel like less of a priority compared to implementing new features.

As to the issue of writing the tests in Python instead to reduce amount of configuration: The configuration involved to run the jest tests is pretty minimal, you only have to go to the relevant test folder and run ```npm test```. On the other hand, I don't see the frontend logic becoming super complicated, so I'm not arguing in favour of using jest/puppeteer because that's easier to integrate with frontend unit tests. 

If you feel very strongly about the cross-browser issue, I'd be happy to look into Selenium (just from my one time experience with Selenium, I found puppeteer much easier to set up, but that might definitely be a personal thing).

**Comment by taymonbeal** [comment]
Do you have your current thing working inside Docker?

**Comment by sebgrebe** [comment]
> Do you have your current thing working inside Docker?

No, you launch the app in one terminal and then the tests in another

**Comment by taymonbeal** [comment]
If you want to check in what you have now so that other people can try running it, that's fine, but I won't consider this issue fixed until we have something that can be made to run in CI. And when it comes time to solve that problem we may need to rethink our approach.

**Comment by sebgrebe** [comment]
Alternative proposal: We could go with [cypress](https://www.cypress.io/). Currently using it at work.
* Would address your browser-worry as it is ([somewhat](https://medium.com/tech-quizlet/cypress-the-future-of-end-to-end-testing-for-web-applications-8ee108c5b255)) cross-browser-compatible 
* It's very user friendly and easy to learn

**Comment by taymonbeal** [comment]
Cypress tests are only sort of end-to-end, and I worry a bit about lock-in. The thing I really like about Selenium is that it works with absolutely everything.

**Comment by taymonbeal** [comment]
For what it's worth, I think it's likely that I'll be setting up the first test myself, to make it work in Docker.

**Comment by sebgrebe** [comment]
> Cypress tests are only sort of end-to-end
Why is that?

**Comment by sebgrebe** [comment]
> For what it's worth, I think it's likely that I'll be setting up the first test myself, to make it work in Docker.

I don't think it's a problem to run [cypress in docker](https://github.com/cypress-io/cypress-docker-images)

**Comment by taymonbeal** [comment]
https://docs.cypress.io/guides/references/trade-offs.html#Inside-the-browser

And yeah, you can definitely run Cypress in Docker, it just sounded like people were worried about setting up Selenium.

Also, it looks like Cypress only supports Chrome right now?

**Comment by sebgrebe** [comment]
> Also, it looks like Cypress only supports Chrome right now?
And [Electron](https://github.com/cypress-io/cypress/issues/310), but yes, it's quite limited.

I take it you started to work on this?

**Comment by taymonbeal** [comment]
We now have one end-to-end test. We still need more.

**Comment by vagarwalla** [comment]
We need to define the end-to-end tests to be scripted.

**Comment by vagarwalla** [comment]
- Need this ASAP after the Forum post to prevent bugs
- Need unit tests, perhaps also write tests as a new feature is being developed

**Comment by sebgrebe** [comment]
Replacing with new issues
