### ISSUE TITLE
Request to add more features to manipulation of profile picture

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#290]
![image](https://user-images.githubusercontent.com/14195560/53124369-091aa200-3510-11e9-8dc4-6ba6007c0278.png)

**Comment by taymonbeal** [comment]
This is technically feasible but not right this second.

**Comment by Richenda** [comment]
Cool. I'll put this on 'soon after launch'. I agree that it's not a priority. 

I also feel that it has somehow gotten lost in all the noise that I also want users to have the option of selecting one of the profile pictures we designed from this list: https://drive.google.com/open?id=1lcBJpLKvgirRJsxPyw3gNb2kP19W9vpb

The reason is that some people prefer not to share photos and do like the convenience and anonymity of going with a provided image. Unless it is crazy costly to implement, of course.
