### ISSUE TITLE
Systematic collection of product feedback a la UserVoice

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#309]
Is this something we should have? I think it's something we should have.

UserVoice proper is stupidly expensive, but getfider.com looks to me like a pretty solid alternative, and it's open source and self-hostable so we can just put it on our Azure account.

**Comment by michaltrzesimiech** [comment]
We should definitely have something like this, but do we need this before the publicised launch @Richenda ?

**Comment by Richenda** [comment]
Can somebody explain to me what this is? I don't really follow.

**Comment by Richenda** [comment]
If I'm totally honest I think this is unecessary, and it definitely shouldn't be anywhere near the forefront of our priorities. The reason I say this is because the Hub's userbase is not typical. We are not going to struggle to get feedback because there are a sizeable number of EAs who give a very strong crap about the site. Even people who don't want there to be a Hub have opinions about it, and I think we're going to get opinions thrown at us constantly. Could uservoice organise those opinions? Yes, in some ways. But do we want a little pop up that says 'how likely would you be to recommend EA Hub to a friend?' Hell no! Honestly just building a good quality form will do just fine. And we will already be needing to do our own custom data gathering exercises for other aspects of the Hub such as local group metrics and the survey. So it's much more logical to roll systematic feedback about the Hub into those processes when we figure them out.

**Comment by taymonbeal** [comment]
Michal suggested to me that we at least see if this could be easily done before the launch. I've set up https://feedback.eahub.org. Curious what people think of it.

**Comment by michaltrzesimiech** [comment]
https://feedback.eahub.org/ looks like a good idea!

**Comment by taymonbeal** [comment]
Should we link this from the main site?

**Comment by michaltrzesimiech** [comment]
Sure, how about the footer?

**Comment by taymonbeal** [comment]
Sounds reasonable to me.
