### ISSUE TITLE
Can signup with a two character password

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/eahub.org#345]
**Problem**
I was able to sign up with a two character long password ('12'). I thought we had a minimum of eight characters in place?

**Solution**
Add minimum for password length and character types

**Comment by taymonbeal** [comment]
Character type restrictions annoy people and don't increase entropy that much. I should look into what modern best practices are for password validation; maybe just checking against haveibeenpwned.com is enough?

**Comment by michaltrzesimiech** [comment]
+1 for being better than character type restrictions, though my competence in this field is too limited to offer solutions. Let me know if it would be useful for me to get more competence ad hoc.

**Comment by taymonbeal** [comment]
I couldn't figure out all the best practices here, so I asked on [Infosec Stack Exchange](https://security.stackexchange.com/questions/205394/what-password-policy-should-a-typical-web-app-have). Hopefully somebody answers.

**Comment by taymonbeal** [comment]
It occurs to me that we should also look into why two-character passwords are being accepted, though. I thought we had an eight-character minimum in place. This might be a bug affecting other password validators too.

**Comment by taymonbeal** [comment]
Okay, the bug is fairly deep in the guts of how we're doing authentication and it might actually require some fairly extensive refactoring in order to fix. Not sure how hard I should prioritize this, given that there's expected to be a mass round of signups as soon as we launch.

**Comment by michaltrzesimiech** [comment]
I expect there to be relatively little cases of users typing in passwords 2 characters long. We can suggest users update their passwords in future communication once we have this fixed. I'd say we should get this fixed if we can, but let's not sacrifice other priorities because of this. We are ok to announce the product without having this issue fixed.

**Comment by michaltrzesimiech** [comment]
One additional idea is to suggest users our guidelines for the passwords they create in text or possibly enforce some basic rules with a simple logic involving regex? Not sure how complex that is in Django.

**Comment by taymonbeal** [comment]
I would like to note for the record that I believe we will need to migrate to [django-allauth](https://django-allauth.readthedocs.io/en/latest/), and doing so pre-launch would make me less nervous from a technical perspective than post-launch. Though I'm guessing we'll probably do it post-launch anyway.

(Some people on EA Discord argued that doing our own authentication at all is insecure and we should go with a third-party service like Auth0, but that seems complicated and different enough that I don't think I want to push for it.)

**Comment by michaltrzesimiech** [comment]
What are some of the worst scenarios that can realistically happen to us with our current setup? I believe identifying those and having a recovery plan is good enough risk management given our current restrictions.

⁣Sent from BlueMail ​

**Comment by taymonbeal** [comment]
Problems I'm aware of that django-allauth would solve:

- We don't enforce the password-strength rules (this bug). If we change that later, we might have to reset some users' passwords, inconveniencing them.
- We have no way of knowing whether users' email addresses are authentic (#355). It is likely that at some point in the future we will start caring about this, and kicking off this process after the fact again risks inconveniencing users.
- We don't have social authentication (#416). Obviously this can be added after the fact with no problems, but I suspect that putting it in before the initial round of emails will increase the number of people who actually follow through and reactivate their accounts, since it means they don't have to come up with a password. This seems desirable.

As for Auth0, I think the case for it is that authentication is generally hard and framework defaults aren't always safe and getting it wrong can result in security incidents, so it's better to just outsource the whole thing to people who specialize in it. (Again, I do not currently advocate doing this.)

**Comment by michaltrzesimiech** [comment]
Let's get back to this before another release.
