### ISSUE TITLE
Data export doesn't include profile picture

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#348]

**Comment by michaltrzesimiech** [comment]
Do we want it to offer it to users? Or is it something we need for technical reasons?

**Comment by taymonbeal** [comment]
We need it for regulatory compliance, at least according to my current understanding.

**Comment by michaltrzesimiech** [comment]
I get it. Thanks for checking that.

**Comment by michaltrzesimiech** [comment]
We seem to be blocked by https://github.com/rtcharity/eahub.org/issues/389

**Comment by taymonbeal** [comment]
There's a semi-related question here of whether this export should be CSV or JSON. CSV can be loaded in Excel, but JSON is nicer for most other purposes. Any thoughts?

**Comment by michaltrzesimiech** [comment]
I'd go for JSON. I don't expect anyone will load their personal profiles into Excel for any reason. It would make sense though to do mass exports to CSV's (because I'd expect some people will like to load bigger datasets into Excel, and we ourselves might want to do that before mass uploading data, should we make that possible). If you think it's best to stick to a single standard (including for just the reason of code reuse), let's do CSV's.

**Comment by taymonbeal** [comment]
I don't think we're going to have general-purpose mass exports, and ones done for particular narrow purposes will probably use whatever format makes sense for that purpose. So I'll go with JSON.
