### ISSUE TITLE
A directory of Facebook groups and pages

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#362]
We were asked to publish this directory of Facebook groups and pages https://www.facebook.com/EffectiveGroups. The decisions to make are:

1. Whether we accept this as part of our product
2. If so, how should it look like?
3. How should it work like (i.e. who can submit, edit a group, or do we use the Facebook API to integrate that automatically?)

**Comment by taymonbeal** [comment]
Can this just be part of the Resource Trail for now?

**Comment by michaltrzesimiech** [comment]
CC @marcinkowrygo

**Comment by Richenda** [comment]
There is no need for a directory on the Hub because the Hub already _is_ a directory. The person who asked probably does not know this because we haven't launched yet. I would explain to that individual that the groups feature we are building already includes details of each group's FB page and group. Of course if their directory is up to date, that's great because we can import that into our existing group data so that it is more up to date. But definitely no new content or feature is needed for this.

**Comment by taymonbeal** [comment]
Most of those Facebook groups don't correspond to geographically local groups. They're more about particular topics.

**Comment by Richenda** [comment]
Oh I see. For that kind they would actually be useful to help us populate the Community section on the home page of the Hub. Right now it only links to the forum. I’ll sketch a wireframe.

**Comment by michaltrzesimiech** [comment]
Moved to https://github.com/rtcharity/resources.eahub.org/issues/381
