### ISSUE TITLE
On /profile/*, if user is an organiser, display information on groups they organise under "Community"

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#380]

**Comment by sebgrebe** [comment]
PR #489 fixes this for now.

Long term, it would be good if we could just add "Organiser" behind the groups a user is the organiser of to avoid double mentioning of groups as here:

![Screen Shot 2019-03-24 at 21 10 18](https://user-images.githubusercontent.com/15908208/54885888-73a95f80-4e79-11e9-9857-2835c6cd6110.png)

Related to this, it would be nice if organisers became automatically group members (as suggested [here](#488)). This would make the display also easier, because then the  display logic wouldn't have to consider cases where someone is organiser, but not member
