### ISSUE TITLE
Update roadmap

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#395]
A bunch of stuff that was on there has since been resolved.

**Comment by sebgrebe** [comment]
Just in the process of updating this, based on Richenda's update [on this spreadsheet](https://docs.google.com/spreadsheets/d/197cZ3HVPsfaw87CChrrGDGhE2aEsRitP2BTLrVs2Ij0/edit#gid=0).

Based on the comments on the spreadsheet, I think the following questions are still open, which probably @Richenda should answer (I'm pulling this discussion here because from experience it's best to have github as single source of truth and it's also easier to ping people):
- Polished admin panel for site admins: @taymonbeal asks whether we want something that's different from what we currently  have on eahub.org/admin. Not sure how you can get access to these @richenda. Once you get access let us know whether you think we should have something prettier.
- Platform for EA projects. 
  - @michaltrzesimiech suggests: 
> "This name likely doesn't tell anything to anyone. Maybe let's be more descriptive with "An independent projects platform"
  - Richenda replies: 
> Sorry I'm not really sure in what way 'independent projects' is any different from 'projects'. To me it sounds less obvious actually?
  --> **Let me know what you want to go with.**
- Appealing and user friendly UI for search feature
  - @michaltrzesimiech suggests: 
> I mean this is functionally a single thing that will be delivered at a single time
  - Richenda replies: 
> Yes but we are just having a list here that describes to users what things will be on it's way. Not what our goals internally look like. It makes it clearer to them what we mean by 'cross platform search'.
I don't know who is 'right' from the POV of how users will see the list. I err on the side of making stuff really obvious even if that means sounding a little silly
  --> **Let me know what you want to go with.**

**Comment by taymonbeal** [comment]
Granting admin access to anyone other than the five people who already have it will require code changes. Open a feature request if this is desired.

**Comment by taymonbeal** [comment]
(Although Richenda could run a local instance and look at the admin panel there.)

**Comment by sebgrebe** [comment]
Screenshots so that @Richenda can get a rough idea
![Screen Shot 2019-03-21 at 21 29 00](https://user-images.githubusercontent.com/15908208/54786438-bd4b3d80-4c20-11e9-99db-4d70645ad25e.png)
![Screen Shot 2019-03-21 at 21 31 06](https://user-images.githubusercontent.com/15908208/54786441-bfad9780-4c20-11e9-8211-3334f6b50ed2.png)

**Comment by Richenda** [comment]
I mean all I need is a screen shot guys 😂

**Comment by Richenda** [comment]
Just put ‘independent’ like Michal asked, because actually it doesn’t really matter one way or the other, I feel.

**Comment by Richenda** [comment]
Oh gosh looks like you posted that just as I posted my suggestion for a screenshot, lol! Thanks for this. That looks perfectly fine for internal use 👍🏻

**Comment by Richenda** [comment]
@sebgrebe we need the CRM removed from the list not because I think it’s done, but because Michal wants us to avoid public commitment to it just yet, as our ideas for it aren’t solidified.

**Comment by sebgrebe** [comment]
Thanks for the answers @Richenda, implemented this. 
I'm closing this. @michaltrzesimiech ping me in case you have strong feelings about only having one feature under search, for now I kept both in as per Richenda's suggestion.
