### ISSUE TITLE
See why Google Analytics doesn't report accurately

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#572]

**Comment by taymonbeal** [comment]
I'm going to need access to our Google Analytics account in order to debug this, probably.

**Comment by michaltrzesimiech** [comment]
Sorry, I was sure I added it

**Comment by taymonbeal** [comment]
What kinds of permissions do I have? I still can't see the tracking code.

**Comment by michaltrzesimiech** [comment]
Edit, Collaborate, Read & Analyze

**Comment by michaltrzesimiech** [comment]
I have just set those again

**Comment by taymonbeal** [comment]
Thanks. Turns out we just flat-out put the wrong tracking ID on our pages. We're supposed to be using UA-130028424-1; I have no idea where the current one (UA-132839837-1) came from.

Do you care about recovering the old analytics data? If so, I can try to figure out if it's been logged to some other account that we could recover access to. Otherwise I'll just switch the tags.

**Comment by michaltrzesimiech** [comment]
Let's just switch the tags, please. We should assume the historical data is lost.
