### ISSUE TITLE
Add messaging

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#586]

**Comment by taymonbeal** [comment]
How is this envisioned to work? Is there just a form that sends someone an email, or something more sophisticated?

**Comment by michaltrzesimiech** [comment]
That's a question to @Richenda (mind that we currently have no time target assigned to this).

**Comment by patbl** [comment]
The MVP would be to allow people to make their email addresses public.

A slightly fancier version would be a form that sends an email (as Taymon suggested). The Reply-To header would be the form-submitter's email address, so that they could continue the conversation by email.

I don't think it's worth trying to build anything fancier. (I suppose there could be an option for disabling the contact form if people asked for it.)

**Comment by michaltrzesimiech** [comment]
@patbl 's suggestions seem very reasonable. I'd start by allowing people to optionally share their email address publicly, then implement a form

CC: @cafelow
