### ISSUE TITLE
Custom profile pictures are gone

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#706]
![image](https://user-images.githubusercontent.com/14195560/57690665-6ec78780-7642-11e9-97b0-a52155b06ecb.png)

**Comment by taymonbeal** [comment]
I'm investigating this now. The original picture files have not been lost; they're still exactly where they're supposed to be, in the blob container. However, the access URLs that Django is generating and including in our pages are getting 403 errors from Azure, because they're missing a mandatory query parameter (`sp`). I have yet to figure out why this parameter is absent, especially since we're using an official Azure client library maintained by Microsoft to generate the URLs. Nor do I have any idea why this suddenly stopped working (does anyone happen to remember the last time it did work?).

**Comment by taymonbeal** [comment]
This turned out to be caused by `azure-storage-python` making a breaking change in their 2.0 release which came out a few days ago, combined with `django-storages` not specifying a maximum major version number, combined with us not pinning our dependencies. I patched our fork of `django-storages`, and will at some point see about getting the fix upstreamed along with some other mitigations.
