### ISSUE TITLE
Access/notifications to personal and group profiles data from the admin panel

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#777]
Implement: 

> I'd like to be able to export data. What I'd like is easy access to - all group data + group organiser names and group organiser email addresses.

**Comment by sebgrebe** [comment]
@cafelow @michaltrzesimiech Is this what we agreed on to do for CEA at least with respect to groups?

**Comment by cafelow** [comment]
Yes please! Thanks for checking in Sebastian. 
1. **Would be helpful soon**: I'd like to be able to export data. What I'd like is easy access to - all group data + group organiser names and group organiser email addresses. 

2. **Would be REALLY great after 1 happens**: I get some sort of a notification when there are changes to the groups database (any change). It could be a weekly report. 

3. **Would be the possibly unrealistic future ideal**: What I REALLY really want is to have a system where it updates CEA's Groups CRM (which I have not created yet), in some way where I can see the most recent changes. I actually think the changes aren't that frequent, so it may be that the time and effort spent on making this system would be greater than the time I spend updating the CRM.   Especially since I often when there is a change I'll have to do some other action (like sending an email to a new group organiser).

**Comment by cafelow** [comment]
Update. Ignore 3. 
2. is still important
1. If 2. is enabled I won't need to export data often. So instead of me exporting data I could ask someone (?) to do a database request for me.

**Comment by cafelow** [comment]
Oops, I asked for this again here:
https://github.com/rtcharity/eahub.org/issues/931
