### ISSUE TITLE
Difficult to access profiles of people from map when their location is the same

### ISSUE THREAD

**Issue by cafelow** [rtcharity/eahub.org#831]
E.g. in Sydney I click on the 38 profiles. Then I can't use down arrow to scroll down, nor take the little scrollbar rectangle and drag it down (I think because it is too close to the x). I instead have to click lower in the scroll bar. 
![image](https://user-images.githubusercontent.com/44737332/66536310-f9240100-eb78-11e9-8e4c-413405b1b8c1.png)

E.g in Wellington there are three profiles, but they are stacked on top of each other and I can only click on the top one. 
![image](https://user-images.githubusercontent.com/44737332/66536496-a26af700-eb79-11e9-9ff1-ff2de74d6109.png)

**Comment by sebgrebe** [comment]
@cafelow 
- Sydney: I can't replicate this, because I don't see "undefined", but "34 anonymous users". I've
![Screen Shot 2019-11-18 at 21 06 34](https://user-images.githubusercontent.com/15908208/69093938-6879f400-0a47-11ea-97ee-ec70cd071c96.png)
I've tried to replicate with another big city, London, and there I don't have any problem with scrolling. Could you check again and tell me how London works for you?
![Screen Shot 2019-11-18 at 21 08 22](https://user-images.githubusercontent.com/15908208/69094055-952e0b80-0a47-11ea-96a1-4f6786af9624.png)

- Wellington: This is super weird, shouldn't happen. My quess is that two users are in the same place and one user is in ALMOST the same place, such that they're not assigned to the same pin, but too close to each other so that you can select between different ones. Need to look into this

**Comment by cafelow** [comment]
@sebgrebe I changed the coordinates for the one rouge Wellingtonian (you were right, they were almost the same location), and I haven't seen that same problem occur again, so I don't think we have to worry about this issue unless it crops up again.

**Comment by patbl** [comment]
Should this issue be closed then?

**Comment by cafelow** [comment]
Yes!
