### ISSUE TITLE
Enhance profile search: Search term box

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/eahub.org#973]
### Current state  
On /profiles, users can only search over profiles for limited information (name, city, country)  

### Desired state  
Users can search over all relevant info for users  
![image](https://user-images.githubusercontent.com/15908208/93709207-4f911200-fb34-11ea-98ce-b5d163f8c23b.png)

### Context  
- Filtering will be done on profile tiles, which will be implemented [here](#969). The present ticket is hence blocked by #969  
- How to implement search will depend on which solution we go with for the tables. See discussion [here](https://github.com/rtcharity/eahub.org/issues/958#issuecomment-695766773)  
- This issue is part of several on search functionality

### Acceptance criteria  
- [ ] Search term box filters the following user fields: name, summary. Ask @vagarwalla whether we're missing any here  
- [ ] wireframe Design is implemented  
- [ ] Is mobile-responsive

**Comment by vagarwalla** [comment]
Per our discussion with @victor-yunenko yesterday, I think the search should be universal and search all searchable fields. Unless there's some issue there? 

Reasoning is because the filters are not exhaustive - e.g. it doesn't search Giving Pledges, Custom areas of expertise etc. I think searching every field is the simplest option. 

Otherwise, it should search all the fields that can't be selected (i.e. ALL text fields) in the filter so eventually that would be: Name, Summary, Needs, Gives, Speaker Description, Custom areas of expertise, possibly other fields I'm not aware of.

**Comment by victor-yunenko** [comment]
I agree, I also intend to index all the fields that aren't filterable through dropdowns 👌

**Comment by victor-yunenko** [comment]
I'll close this ticket for now then - since with Algolia we shouldn't have problems with search through all the available fields 👌
